version: "3.7"
services:
  dogfooter_control:
    image: dogfooter/dogfooter-control-dev:latest
    volumes:
      - type: bind
        source: .
        target: /go/src/dogfooter-control
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "1.0"
         memory: 1000M
    networks:
      - dogfooter_network
    ports:
      - 8090:8080
networks:
  dogfooter_network:
