version: "3.7"
services:
  dogfooter_control:
    image: dogfooterm/dogfooter-control-dev:latest
    volumes:
      - type: bind
        source: .
        target: /go/src/dogfooter-control
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "1.0"
         memory: 1000M
    ports:
      - 9000:8080
