version: "3.7"
services:
  dogfooter_control:
    image: dogfooter/dogfooter-control:latest
    volumes:
      - type: bind
        source: /home/dogfooter
        target: /var/local
    deploy:
      replicas: 2 
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "0.1"
         memory: 100M
    networks:
      - deploy_network
    ports:
      - 1126:8080
networks:
  deploy_network:
volumes:
  dogfooter_control_volume:
    external: true
