version: "3.2"
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - deploy_network
    volumes:
      - type: volume
        source: dogfooter_redis_volume
        target: /data
    ports:
      - 8082:6379
networks:
  deploy_network:
  dogfooter_network:
volumes:
  dogfooter_redis_volume:
    external: true
