version: "3.2"
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - type: volume
        source: pawpad_redis_volume
        target: /data
    ports:
      - 9092:6379
  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=pawpad_redis:pawpad_redis:6379
    ports:
    - 9003:8081
  system_mongodb:
    image: 'mongo:3.6'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=hotice1234
    volumes:
      - type: volume
        source: pawpad_system_db_volume
        target: /data/db
  system_mongodb_express:
    image: 'mongo-express:latest'
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=hotice1234
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=pawpad_system_mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hotice1234
    ports:
      - 9001:8081
volumes:
  pawpad_system_db_volume:
    external: true
  pawpad_redis_volume:
    external: true
