// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiRequest) Reset()         { *m = ApiRequest{} }
func (m *ApiRequest) String() string { return proto.CompactTextString(m) }
func (*ApiRequest) ProtoMessage()    {}
func (*ApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *ApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiRequest.Unmarshal(m, b)
}
func (m *ApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiRequest.Marshal(b, m, deterministic)
}
func (m *ApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiRequest.Merge(m, src)
}
func (m *ApiRequest) XXX_Size() int {
	return xxx_messageInfo_ApiRequest.Size(m)
}
func (m *ApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiRequest proto.InternalMessageInfo

type ApiReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiReply) Reset()         { *m = ApiReply{} }
func (m *ApiReply) String() string { return proto.CompactTextString(m) }
func (*ApiReply) ProtoMessage()    {}
func (*ApiReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *ApiReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiReply.Unmarshal(m, b)
}
func (m *ApiReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiReply.Marshal(b, m, deterministic)
}
func (m *ApiReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiReply.Merge(m, src)
}
func (m *ApiReply) XXX_Size() int {
	return xxx_messageInfo_ApiReply.Size(m)
}
func (m *ApiReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiReply.DiscardUnknown(m)
}

var xxx_messageInfo_ApiReply proto.InternalMessageInfo

type RootRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootRequest) Reset()         { *m = RootRequest{} }
func (m *RootRequest) String() string { return proto.CompactTextString(m) }
func (*RootRequest) ProtoMessage()    {}
func (*RootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{2}
}

func (m *RootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootRequest.Unmarshal(m, b)
}
func (m *RootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootRequest.Marshal(b, m, deterministic)
}
func (m *RootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootRequest.Merge(m, src)
}
func (m *RootRequest) XXX_Size() int {
	return xxx_messageInfo_RootRequest.Size(m)
}
func (m *RootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RootRequest proto.InternalMessageInfo

type RootReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootReply) Reset()         { *m = RootReply{} }
func (m *RootReply) String() string { return proto.CompactTextString(m) }
func (*RootReply) ProtoMessage()    {}
func (*RootReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{3}
}

func (m *RootReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RootReply.Unmarshal(m, b)
}
func (m *RootReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RootReply.Marshal(b, m, deterministic)
}
func (m *RootReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootReply.Merge(m, src)
}
func (m *RootReply) XXX_Size() int {
	return xxx_messageInfo_RootReply.Size(m)
}
func (m *RootReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RootReply.DiscardUnknown(m)
}

var xxx_messageInfo_RootReply proto.InternalMessageInfo

type FileRequest struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	File                 string   `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Separators           []string `protobuf:"bytes,5,rep,name=separators,proto3" json:"separators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{4}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *FileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *FileRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *FileRequest) GetSeparators() []string {
	if m != nil {
		return m.Separators
	}
	return nil
}

type FileReply struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	StaticFilePath       string   `protobuf:"bytes,2,opt,name=static_file_path,json=staticFilePath,proto3" json:"static_file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReply) Reset()         { *m = FileReply{} }
func (m *FileReply) String() string { return proto.CompactTextString(m) }
func (*FileReply) ProtoMessage()    {}
func (*FileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{5}
}

func (m *FileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReply.Unmarshal(m, b)
}
func (m *FileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReply.Marshal(b, m, deterministic)
}
func (m *FileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReply.Merge(m, src)
}
func (m *FileReply) XXX_Size() int {
	return xxx_messageInfo_FileReply.Size(m)
}
func (m *FileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReply.DiscardUnknown(m)
}

var xxx_messageInfo_FileReply proto.InternalMessageInfo

func (m *FileReply) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *FileReply) GetStaticFilePath() string {
	if m != nil {
		return m.StaticFilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*ApiRequest)(nil), "pb.ApiRequest")
	proto.RegisterType((*ApiReply)(nil), "pb.ApiReply")
	proto.RegisterType((*RootRequest)(nil), "pb.RootRequest")
	proto.RegisterType((*RootReply)(nil), "pb.RootReply")
	proto.RegisterType((*FileRequest)(nil), "pb.FileRequest")
	proto.RegisterType((*FileReply)(nil), "pb.FileReply")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d) }

var fileDescriptor_0c5120591600887d = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xc9, 0x1f, 0x4f, 0x33, 0xf9, 0xa3, 0x4c, 0x21, 0xe1, 0x0a, 0x39, 0x23, 0x48, 0xaa,
	0x14, 0xfa, 0x09, 0x0e, 0xc1, 0x4e, 0x90, 0x60, 0x1f, 0x36, 0xc9, 0x4a, 0x16, 0xe3, 0xed, 0x9a,
	0x1d, 0x8b, 0x6b, 0xfc, 0x04, 0x7e, 0x68, 0xd9, 0xdd, 0x78, 0x97, 0xe6, 0xba, 0xbc, 0xdf, 0x1b,
	0x66, 0x5e, 0xde, 0x42, 0xda, 0xc9, 0x1d, 0x4d, 0x72, 0xac, 0xd4, 0x24, 0x49, 0xa2, 0xaf, 0xda,
	0x22, 0x01, 0xd8, 0x2a, 0x51, 0xf3, 0xaf, 0x6f, 0xae, 0xa9, 0x00, 0xb8, 0xb0, 0x4a, 0x8d, 0xfb,
	0x22, 0x85, 0xb8, 0x96, 0x92, 0xfe, 0xad, 0x18, 0x22, 0x27, 0x8d, 0xf7, 0xeb, 0x41, 0xfc, 0x2c,
	0x46, 0x3e, 0x9b, 0x78, 0x0d, 0xab, 0x4f, 0x4e, 0x83, 0xec, 0x73, 0x6f, 0xe3, 0x95, 0x51, 0x3d,
	0x2b, 0xcc, 0xc0, 0x17, 0x7d, 0xee, 0x5b, 0xe6, 0x8b, 0x1e, 0x6f, 0x21, 0x61, 0x5d, 0xc7, 0xb5,
	0x6e, 0x48, 0x7e, 0xf0, 0x5d, 0x1e, 0x58, 0x27, 0x76, 0xec, 0xcd, 0x20, 0x44, 0x08, 0xdf, 0xc5,
	0xc8, 0xf3, 0xd0, 0x5a, 0xf6, 0x1b, 0x6f, 0x00, 0x34, 0x57, 0x6c, 0x62, 0x24, 0x27, 0x9d, 0x9f,
	0x6d, 0x82, 0x32, 0xaa, 0x17, 0xa4, 0x78, 0x81, 0xc8, 0xa5, 0x51, 0xe3, 0xfe, 0x64, 0x96, 0x12,
	0xae, 0x34, 0x31, 0x12, 0x5d, 0x63, 0x76, 0x36, 0x8a, 0xd1, 0x30, 0x27, 0xcb, 0x1c, 0x37, 0x2b,
	0x5e, 0x19, 0x0d, 0x0f, 0x3f, 0x70, 0xfe, 0xe4, 0x8a, 0xc2, 0x3b, 0x08, 0xb6, 0x4a, 0x60, 0x56,
	0xa9, 0xb6, 0x3a, 0xf6, 0xb4, 0x4e, 0x0e, 0xda, 0x5c, 0xbc, 0x87, 0xd0, 0x54, 0x83, 0x97, 0x86,
	0x2e, 0x3a, 0x5b, 0xa7, 0x47, 0x30, 0xcf, 0x99, 0x1b, 0x6e, 0x6e, 0x51, 0x9f, 0x9b, 0x3b, 0xfc,
	0x41, 0xbb, 0xb2, 0xcf, 0xf3, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x28, 0x21, 0xa7, 0x36, 0xaf,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	Api(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*ApiReply, error)
	Root(ctx context.Context, in *RootRequest, opts ...grpc.CallOption) (*RootReply, error)
	File(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Api(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*ApiReply, error) {
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, "/pb.Control/Api", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Root(ctx context.Context, in *RootRequest, opts ...grpc.CallOption) (*RootReply, error) {
	out := new(RootReply)
	err := c.cc.Invoke(ctx, "/pb.Control/Root", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) File(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileReply, error) {
	out := new(FileReply)
	err := c.cc.Invoke(ctx, "/pb.Control/File", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	Api(context.Context, *ApiRequest) (*ApiReply, error)
	Root(context.Context, *RootRequest) (*RootReply, error)
	File(context.Context, *FileRequest) (*FileReply, error)
}

// UnimplementedControlServer can be embedded to have forward compatible implementations.
type UnimplementedControlServer struct {
}

func (*UnimplementedControlServer) Api(ctx context.Context, req *ApiRequest) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Api not implemented")
}
func (*UnimplementedControlServer) Root(ctx context.Context, req *RootRequest) (*RootReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Root not implemented")
}
func (*UnimplementedControlServer) File(ctx context.Context, req *FileRequest) (*FileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method File not implemented")
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_Api_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Api(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Control/Api",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Api(ctx, req.(*ApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Root_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Root(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Control/Root",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Root(ctx, req.(*RootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_File_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).File(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Control/File",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).File(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Api",
			Handler:    _Control_Api_Handler,
		},
		{
			MethodName: "Root",
			Handler:    _Control_Root_Handler,
		},
		{
			MethodName: "File",
			Handler:    _Control_File_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
